#!/usr/bin/env bash

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#

#If you change the name of the executable, the directory structure of
#and config file of any blog you create with the newly named script
#will reflect it.
progname="$(basename $0)"
progauthor="Jose Anthony Agudo"
progweb="https://github.com/antoniusmisfit/omicron/"

do_help()
{
cat << EOF
$progname: A tiny single-page HTML5 blog engine suitable for text-based browsers.

Usages:
$progname [-e postname] [-d postname] -c -l -h

-e postname	Create or edit an entry to a blog. If blog does not exist, it is created.
-d postname	Delete a specified blog entry and update the blog accordingly.
-l			List the entry names in the current blog.
-c			Edit the blog configuration file and update the blog accordingly.
-h			Show this help page.

Notes:
When creating a new entry to the blog, $progname uses the first line of the file as the title of the entry, and from the third to last line as the post body.
EOF
}

get_config()
{
if [ -e ./.$progname.config ];then
	source ./.$progname.config
else
	cat > ./.$progname.config << EOF
blogtitle="untitled"
blogauthor="$(whoami)"
font="sans"
css="light"
webroot="http://localhost:8000"
EOF
	source ./.$progname.config
fi
}

init_blog()
{
get_config
#A couple of CSS themes for the blog. Feel free to create your own as you see fit.
if [ ! -e ./.$progname/ ];then
	mkdir -p ./.$progname
fi
cat > ./.$progname/light.css << EOF
html{font-family: "$font";background-color: white;color: black}
#rss{text-align: center;color: orange}
#footer,#header,#nav{text-align: center;color: white;background-color: royalblue}
EOF
cat > ./.$progname/dark.css << EOF
html{font-family: "$font";background-color: black;color: white}
#rss{text-align: center;color: orange}
#footer,#header,#nav{text-align: center;color: white;background-color: darkred}
EOF
}

gen_index()
{
cat > ./index.html << EOF
<!doctype html>
<html>
<head>
<title>$blogtitle</title>
<link rel="stylesheet" type="text/css" href="$webroot/.$progname/$css.css">
</head>
<body>
<div id="header">$blogtitle</div>
<pre>
EOF
for eachfile in $(ls -c ./.$progname/*.raw); do
if [ -e $eachfile ];then
cat >> ./index.html << EOF
<article id="$(basename $eachfile .raw)">
<a href="#$(basename $eachfile .raw)"><strong>$(head -n 1 $eachfile)</strong></a>

$(fmt -s $eachfile | tail -n +3)
<a href="https://www.facebook.com/sharer/sharer.php?u=$webroot/index.html#$(basename $eachfile .raw)">[Share to Facebook]</a> <a href="https://twitter.com/share?url=$webroot/index.html#$(basename $eachfile .raw)">[Share to Twitter]</a>
</article>
EOF
fi
done
cat >> ./index.html << EOF
</pre>
<div id ="footer">
Powered by $progname. Copyright &copy; 2015-$(date "+%Y") <a href="$progweb" target="_blank">$progauthor</a>
</div>
<div id="rss">
<a href="$webroot/.$progname/rss.xml">RSS</a>
</div>
</body>
</html>
EOF
}

gen_rss()
{
get_config
cat > ./.$progname/rss.xml << EOF
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
<channel>
<title>$blogtitle</title>
<link>$webroot</link>
<description>$blogtitle</description>
<language>en-us</language>
EOF
for eachfile in $(ls -c ./.$progname/*.raw);do
cat >> ./.$progname/rss.xml << EOF
<item>
<title>$(head -n 1 $eachfile)</title>
<link>$webroot/index.html#$(basename $eachfile .raw)</link>
<description>$(tail -n +3 $eachfile | fmt -s | head -n 3)</description>
<guid>$webroot/index.html#$(basename $eachfile .raw)</guid>
</item>
EOF
done
cat >> ./.$progname/rss.xml << EOF
</channel>
</rss>
EOF
}

while getopts "e:d:cmlh" option ;do
	case "$option" in
		e) mkdir -p ./.$progname;vim ./.$progname/${OPTARG}.raw;;
		d) rm ./.$progname/${OPTARG}.raw;;
		c) get_config;vim ./.$progname.config;;
		l) for eachfile in ./.$progname/*.raw;do echo $(basename $eachfile .raw);done;exit;;
		h) do_help;exit;;
		*) do_help;exit;;
	esac
done
init_blog
gen_index
gen_rss